# This is a basic workflow to help you get started with Actions

name: NPM

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [develop]
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  normal-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Xvfb libxss1
        run: sudo apt-get install xvfb libxss1
      - name: remove
        run: rm -rf node_modules yarn.lock package-lock.json
      - name: yarn
        run: yarn install --ignore-platform
      - name: build
        run: yarn run build
      - name: test
        run: yarn run test:e2e
