# This is a basic workflow to help you get started with Actions

name: Cypress

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [develop]
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  single:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: cypress-io/github-action@v2
        with:
          working-directory: examples/start-and-yarn-workspaces/workspace-1
          build: yarn build:ci
          start: yarn test:ci
          wait-on: 'http://localhost:8080'
