# This is a basic workflow to help you get started with Actions

name: Cypress

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [develop]
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        uses: cypress-io/github-action@v1
        with:
          install: yarn build:ci
      - run: yarn lint
      - name: tests 🧪
        uses: cypress-io/github-action@v1
        with:
          command: yarn test:ci
